#!/usr/bin/env python3
"""Cut the font tables and the CTCSS table out of the firmware sources so the
simulator renders with exactly the same glyphs as the radio."""
import re, sys, os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
def grab(path, start_pat):
    s = open(os.path.join(root, path)).read()
    i = s.index(start_pat)
    j = s.index("};", i) + 2
    return s[i:j]
out = ["/* generated by tests/sim/extract.py - do not edit */", "#include <stdint.h>"]
out.append(grab("src/app/display.c", "static const uint8_t font5x7[95][5]"))
out.append(grab("src/drivers/lcd.c", "static const uint8_t font8x8[]"))
out.append(grab("src/drivers/bk4829.c", "const uint16_t ctcss_tone_table[CTCSS_TONE_COUNT]"))
open(sys.argv[1], "w").write("\n".join(out) + "\n")
